###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

OutputType = TypeVar('OutputType')

# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlSyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client

    
    def GenerateMusic_AnthropicHaiku(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_AnthropicHaiku",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_AnthropicOpus(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_AnthropicOpus",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_AnthropicSonnet(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_AnthropicSonnet",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_DeepseekReasoner(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_DeepseekReasoner",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_Gemini15Flash(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_Gemini15Flash",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_Gemini15Pro(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_Gemini15Pro",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_Gemini20FlashExp(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_Gemini20FlashExp",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_Gemini20FlashThinkingExp(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_Gemini20FlashThinkingExp",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_HyperbolicDeepseekReasoner(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_HyperbolicDeepseekReasoner",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_OpenAIGPT4o(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_OpenAIGPT4o",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_OpenAIo1(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_OpenAIo1",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_OpenAIo1Mini(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_OpenAIo1Mini",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    
    def GenerateMusic_OpenAIo3Mini(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RoundedBinaryPiece:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.call_function_sync(
        "GenerateMusic_OpenAIo3Mini",
        {
          "theme": theme,"prompt": prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.RoundedBinaryPiece, raw.cast_to(types, types, partial_types, False))
    



class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def GenerateMusic_AnthropicHaiku(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_AnthropicHaiku",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_AnthropicOpus(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_AnthropicOpus",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_AnthropicSonnet(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_AnthropicSonnet",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_DeepseekReasoner(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_DeepseekReasoner",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_Gemini15Flash(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_Gemini15Flash",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_Gemini15Pro(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_Gemini15Pro",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_Gemini20FlashExp(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_Gemini20FlashExp",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_Gemini20FlashThinkingExp(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_Gemini20FlashThinkingExp",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_HyperbolicDeepseekReasoner(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_HyperbolicDeepseekReasoner",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_OpenAIGPT4o(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_OpenAIGPT4o",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_OpenAIo1(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_OpenAIo1",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_OpenAIo1Mini(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_OpenAIo1Mini",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def GenerateMusic_OpenAIo3Mini(
        self,
        theme: str,prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function_sync(
        "GenerateMusic_OpenAIo3Mini",
        {
          "theme": theme,
          "prompt": prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlSyncStream[partial_types.RoundedBinaryPiece, types.RoundedBinaryPiece](
        raw,
        lambda x: cast(partial_types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.RoundedBinaryPiece, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    

b = BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]